name: rich_clipboard
description: Flutter plugin for accessing rich text and other data types in the system clipboard.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  rich_clipboard_macos:
    path: ../rich_clipboard_macos
  rich_clipboard_windows:
    path: ../rich_clipboard_windows
  rich_clipboard_linux:
    path: ../rich_clipboard_linux
  rich_clipboard_web:
    path: ../rich_clipboard_web
  rich_clipboard_android:
    path: ../rich_clipboard_android
  rich_clipboard_ios:
    path: ../rich_clipboard_ios
  rich_clipboard_platform_interface:
    path: ../rich_clipboard_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        default_package: rich_clipboard_macos
      windows:
        default_package: rich_clipboard_windows
      linux:
        default_package: rich_clipboard_linux
      web:
        default_package: rich_clipboard_web
      android:
        default_package: rich_clipboard_android
      ios:
        default_package: rich_clipboard_ios
